---
title: "smcfcs- vignette in progress"
author: "Jonathan Bartlett"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{smcfcs}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

## Introduction

Missing data are a common issue in many fields of empirical research. An extremely popular approach to handling missing data is the method of multiple imputation (MI). Multiple imputation involves replacing missing values by a number of imputations, creating multiple imputed datasets. Each completed dataset is then analysed as usual, and estimates and standard errors are combined across imputations using rules developed by Rubin.

The most popular approach to imputation uses parametric models for the missing variables given the observed. Multiple imputation gives valid inferences provided that the missing data satisfy the so called missing at random (MAR) assumption and that the imputation models used are correctly specified.

### Joint model and FCS multiple imputation

When multiple variables are affected by missingness, a joint multivariate model can be specified for the partially observed variables. A popular alternative is the fully conditional specification (FCS) approach. Rather than imputing directly from a joint model, FCS MI involves, for each partially observed variable, specifying and imputing from a conditional model in which the other variables (partially observed and fully observed) serve as predictors.

### Imputation model compatibility

When missing values are imputed from a misspecified model, in general invalid inferences will result. One way in which misspecification can occur is when the imputation and substantive model of interest are incompatible. That is, there exists no joint model which contains the imputation model and the substantive model as the corresponding conditionals. In this case, as described by <a href="http://doi.org/10.1177/0962280214521348">Bartlett *et al* (2014)</a>, assuming that the substantive model is correctly specified, unless the imputation and substantive models can be made compatible by imposing a restriction on the imputation model, incompatiblity implies the imputation model is misspecified.

Such incompatibility between the imputation model used to impute a partially observed covariate and the substantive/outcome model can arise for example when the latter includes interactions or non-linear effects of variables. In these cases, it may be difficult or impossible to specify a compatible imputation model for a covariate using standard imputation models as available in existing packages.

## Substantive Model Compatible Fully Conditional Specification multiple imputation
The substantive model compatible modification of the fully conditional specification (sometimes referred to as chained equations) imputation approach, proposed by <a href="http://doi.org/10.1177/0962280214521348">Bartlett *et al* (2014)</a>, ensures that each partially observed variable is imputed from an imputation which is compatible with the user specific model for the outcome (the substantive model).

## Imputing using auxiliary variables with smcfcs

One of the strengths of multiple imputation in general is the possibility to use variables in imputation models which are subsequently not involved in the substantive model. This may be useful in order to condition or adjust for variables which are predictive of missingness, but which are not used in the substantive model of interest. Alternatively conditioning on auxiliary variables which are strongly correlated with one or more variables which are being imputed improves efficiency.

When using smcfcs to impute missing covariates, auxiliary variables V can be added conditioned on by adding them to the substantive/outcome model as additional covariates. Once the imputed datasets have been generated, the actual substantive model of interest, which does not include the auxiliaries, can be fitted. For outcome models other than linear regression, this approach is not entirely justified due to the lack of collapsibility of non-linear models. For example, if a Cox model is assumed for a failure time given variables X and V, the hazard function given only X (i.e. omitting V from the model) is no longer a Cox model. Further research is warranted to explore how this might affect the resulting inferences. If desired, one can include 

## Assessing convergence ##
Like standard chained equations or FCS imputation, the SMC-FCS algorithm must be run for a sufficient number of iterations for the process to converge to its stationary distribution. The default number of iterations used is 10, but this may not be sufficient in any given dataset and model specifcication. To assess convergence, the object returned by smcfcs includes an object called smCoefIter. This matrix contains the parameter estimates of the substantive model, and is indexed by imputation number, parameter number, and iteration number. To assess convergence, one can call smcfcs with m=1 and numit suitably chosen (e.g. 100). The values in the resulting smCoefIter matrix can then be plotted to assess convergence.

## Future plans

Currently the smcfcs package does not handle missing outcomes (except that for time to event of competing risks data, censoring is of course allowed for). In a future version the facility to impute missing outcomes will be added when the substantive model is a linear or logistic regression model.

<h2 id="references">References</h3>

Bartlett JW, Seaman SR, White IR, Carpenter JR. Multiple imputation of covariates
by fully conditional specification: accommodating the substantive model. 
<a href="http://doi.org/10.1177/0962280214521348">Statistical Methods in Medical Research (2014)</a>
